# Welcome to Jekyll!


# Site settings
title: Athena Designs
description: Athena Designs, Calculator, Sports Feed, Website Designs, Codeword builder
baseurl: ""
url: "http://www.athena-designs.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

theme:
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag